title = "shiritori-game gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "Allowlisted paths and patterns"
paths = [
  '''package-lock\.json$''',
  '''\.github/workflows/.*''',
  '''src/data/dictionary\.json$''',
  '''shiritori_flutter/lib/firebase_options\.dart$''',
  '''shiritori_flutter/android/app/google-services\.json$''',
  '''shiritori_flutter/ios/Runner/GoogleService-Info\.plist$''',
]
