// File generated by FlutterFire CLI (web). Android/iOS entries added for scaffolded builds.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Desktop builds are scaffolded only. Use web or mobile for Firebase: '
          'flutter run -d chrome',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOr3y32r7OG1EfX6728LRK4hR7rHV7x_k',
    appId: '1:324507601155:web:d69804f7cf3dba96ec4136',
    messagingSenderId: '324507601155',
    projectId: 'shiritori-game-ccaae',
    authDomain: 'shiritori-game-ccaae.firebaseapp.com',
    databaseURL: 'https://shiritori-game-ccaae-default-rtdb.firebaseio.com',
    storageBucket: 'shiritori-game-ccaae.firebasestorage.app',
    measurementId: 'G-9X4LT2R6CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqrOdxX5qpThctLpYDh4qgBefYzOEV0bE',
    appId: '1:324507601155:android:1e8c704834cf594fec4136',
    messagingSenderId: '324507601155',
    projectId: 'shiritori-game-ccaae',
    databaseURL: 'https://shiritori-game-ccaae-default-rtdb.firebaseio.com',
    storageBucket: 'shiritori-game-ccaae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMd_9Csf5bBi1fMg0CsofHjEFLpJPmFsk',
    appId: '1:324507601155:ios:45bb4ebcba9ae116ec4136',
    messagingSenderId: '324507601155',
    projectId: 'shiritori-game-ccaae',
    databaseURL: 'https://shiritori-game-ccaae-default-rtdb.firebaseio.com',
    storageBucket: 'shiritori-game-ccaae.firebasestorage.app',
    iosBundleId: 'com.shiritori.shiritoriFlutter',
  );
}
