input {
  http {
    port => 5044
    codec => json
  }
}

filter {
  if [service] {
    mutate { add_field => { "[@metadata][index]" => "shiritori-health-pulse" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "shiritori-health-pulse-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
